version: '3.8'

services:
  bot:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    networks:
      - bot_network

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data: 